#!/bin/sh
#
# AudioTranscode - a python interface to transcode using CLI-codecs
# Copyright (c) 2013 Tom Wallroth
#
# licensed under GNU GPL version 3 (or later)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
##############################################################################
#
# run a number of tests for the project
#
##############################################################################

PROJECTDIR=`dirname $0`
echo ${PROJECTDIR}
TESTDIR=${PROJECTDIR}/test

if [ ! -d ${PROJECTDIR} ]; then
    echo "PROJECTDIR not set correctly? to fix, edit $0" >&2
    exit 1
fi

echo "running unit tests..."
nosetests3 --nocapture
if [ $? != 0 ]; then
    echo "unit test(s) failed" >&2
    exit 1
fi

